main: me.Adelemphii.LightningTools.Main
name: LightningTools
version: 1.0
author: Adelemphii
api-version: 1.13

commands:
  LightningSword:
    aliases: ls
    description: Summons a Lightning Sword which is imbued with the power of the gods.